### ISSUE TITLE
Figure out how to pull data from ArcGIS and Esri maps

### ISSUE THREAD

**Issue by lazd** [lazd/coronadatascraper#1]
A number of site have ArcGIS and Esri maps. It should be possible to pull their data directly.

ArcGIS example: https://www.nj.gov/health/cd/topics/covid2019_dashboard.shtml
ERIS example: https://www.ncdhhs.gov/covid-19-case-count-nc

https://github.com/CSSEGISandData/COVID-19/issues/558#issuecomment-599001698

**Comment by tavyandy97** [comment]
Hey! What all data do you want from the aforementioned sources?

**Comment by mark-otaris** [comment]
You can download the data as a CSV.

Dashboard | Directory page | Data
--------- | -------------- | ----
[New Jersey](https://www.nj.gov/health/cd/topics/covid2019_dashboard.shtml) | [Counties](https://services7.arcgis.com/Z0rixLlManVefxqY/arcgis/rest/services/Counties/FeatureServer) | [CSV](https://opendata.arcgis.com/datasets/8840fd8ac1314f5188e6cf98b525321c_0.csv)
[North Carolina](https://www.ncdhhs.gov/covid-19-case-count-nc) | [NCCovid19](https://services.arcgis.com/iFBq2AW9XO0jYYF7/arcgis/rest/services/NCCovid19/FeatureServer) | [CSV](https://opendata.arcgis.com/datasets/969678bce431494a8f64d7faade6e5b8_0.csv)

**Comment by lazd** [comment]
@mark-otaris you're a hero. Can you identify [the other states from here](https://docs.google.com/spreadsheets/d/1T2cSvWvUvurnOuNFj2AMPGLpuR2yVs3-jdd_urfWU4c/edit#gid=0) that might provide this data and post back with links?

**Comment by lazd** [comment]
@mark-otaris already got those CSVs added to the scraper, excellent work!

**Comment by mark-otaris** [comment]
Added Indiana.

**Comment by lazd** [comment]
Closing this now that we've got it covered. Thanks again!

**Comment by SteveWallace** [comment]
@mark-otaris any chance you could figure out Lousiana's? http://ldh.la.gov/Coronavirus/ not familiary enough with the arcGIS api to know where to get the proper link

**Comment by mark-otaris** [comment]
I added the CSV for Lousiana; it has cases and deaths for each parish, which Wikipedia says are equivalent to counties.

**Comment by SteveWallace** [comment]
Thanks!

**Comment by lazd** [comment]
Updated, thanks @mark-otaris!

@SteveWallace look at the scraper, I did the hacky bit we talked about and added a conditional based on date... It'll parse the old date before today, and the CSV going forward.

**Comment by lazd** [comment]
@mark-otaris do these URLs stay up to date? Also, how are you getting them?

Can you get a URL for https://coronavirus.maryland.gov/'s CSV?

**Comment by lazd** [comment]
@mark-otaris I figured it out, inspect until you find the request to https://services.arcgis.com/ FeatureServer, pull the `serviceItemId` from the response, then do `http://opendata.arcgis.com/datasets/${serviceItemId}_0.csv`. Thanks!

**Comment by mark-otaris** [comment]
Yes, and the 0 after the underscore is the number of the layer. Most of them have only one layer, but JHU CSSE has three.
