### ISSUE TITLE
Missing location and population data for ESP regions

### ISSUE THREAD

**Issue by lazd** [lazd/coronadatascraper#103]
Tons of ESP regions can't find their respective GeoJSON:

  ❌ Could not find location Principado de Asturias, ESP
  ❌ Could not find location Illes Balears, ESP
  ❌ Could not find location Canarias, ESP
  ❌ Could not find location Comunitat Valenciana, ESP
  ❌ Could not find location Comunidad de Madrid, ESP
  ❌ Could not find location Región de Murcia, ESP
  ❌ Could not find location Comunidad Foral de Navarra, ESP

And we're missing population data for tons too:

  ❌ Andalucía, ESP: ?
  ❌ Aragón, ESP: ?
  ❌ Principado de Asturias, ESP: ?
  ❌ Illes Balears, ESP: ?
  ❌ Canarias, ESP: ?
  ❌ Cantabria, ESP: ?
  ❌ Castilla y León, ESP: ?
  ❌ Castilla-La Mancha, ESP: ?
  ❌ Cataluña, ESP: ?
  ❌ Comunitat Valenciana, ESP: ?
  ❌ Extremadura, ESP: ?
  ❌ Galicia, ESP: ?
  ❌ Comunidad de Madrid, ESP: ?
  ❌ Región de Murcia, ESP: ?
  ❌ Comunidad Foral de Navarra, ESP: ?
  ❌ País Vasco, ESP: ?
  ❌ La Rioja, ESP: ?
  ❌ Ceuta, ESP: ?
  ❌ Melilla, ESP: ?

**Comment by veyEskelson** [comment]
http://www.diva-gis.org/datadown

Spain Administrative areas. ESP_Adm1.shx should be the boundaries you want. 

[ESP_adm1_json.zip](https://github.com/lazd/coronadatascraper/files/4344060/ESP_adm1_json.zip)

**Comment by veyEskelson** [comment]
Population numbers
https://www.ine.es/dynt3/inebase/en/index.htm?padre=517&capsel=525

Municipal breakdown-Download compressed file with the municipal Excel files for each year (latest population totals from January 2019)
Downloadable  in CSV and Json

**Comment by HerbCaudill** [comment]
this is fixed by #228 and https://github.com/lazd/coronavirus-data-sources/pull/8 . Problem was that data is reported by Comunidad Autónoma, but geojson only showed Provincias.
