### ISSUE TITLE
Generate scorecards for data sources based on ratings, publish on site

### ISSUE THREAD

**Issue by lazd** [lazd/coronadatascraper#108]
In order to convince counties and states to provide good data, we should have a scorecard with big angry colored grades from A+ to F- to rate data sources.

**Comment by camjc** [comment]
Yes! And ideally “why” we think it’s a bad source, as well as what formats give an A rating.

**Comment by lazd** [comment]
Closed by b8c34bae71556cea9c6a0089d58ee1c239b33a75

@camjc let me know what you think of the explanations here: https://blog.lazd.net/coronadatascraper/#sources
