### ISSUE TITLE
Add contributor field to scrapers, contributors page to website

### ISSUE THREAD

**Issue by lazd** [lazd/coronadatascraper#121]
This could contain the github username or Slack handle of the person who contributed the scraper. That way we can link to them from the Sources page (and bug them on Slack when their scraper breaks 😈)

**Comment by lazd** [comment]
I'm thinking:
```
    contributors: [{
      github: 'lazd',
      twitter: '@lazdnet',
      slack: 'lazd'
    }],
```
@qgolsteyn @osvyg @camjc thoughts?

**Comment by lazd** [comment]
Once we have this data, we can generate a `Contributors` page for the website

**Comment by lazd** [comment]
Contributors is pretty vague... how about `engineer(s)`? This is going to appear in the data... I considered `scraperAuthor` but it's a little weird

**Comment by qgolsteyn** [comment]
`author` takes a format similar to `package.json`, so I don't see it as being too vague. `maintainer` could be an alternative.

**Comment by lazd** [comment]
`maintainer` speaks to me... If I saw raw CSV data with an `author` field, it would be confusing...

**Comment by ryanblock** [comment]
Personally I prefer `authors` since there are potentially many ways to contribute, such as pointing out a URL changed (but not actually writing any code). Either is fine though, pick whatever you like best and let's roll with it!
