### ISSUE TITLE
GPS data seems off for some US entries, example below. 

### ISSUE THREAD

**Issue by Rathna-K** [lazd/coronadatascraper#130]
the below is an example of the timeseries.csv where the GPS location seems off even though the source link in the entry seems to have different i think? 
```
,,LA,USA,4648794,10.715987449983892,106.13383655129704,https://opendata.arcgis.com/datasets/79e1165ecb95496589d39faa25a83ad4_0.csv,1,,,1,,,2020-03-10
```

**Comment by lazd** [comment]
So the GPS data is being determined by finding the center of the polygon representing the location. It's possible we got a different number than someone else; did you check to see if it still falls within Louisiana?

**Comment by Rathna-K** [comment]
yes it is showing somewhere in Africa. :)

**Comment by lazd** [comment]
Thanks for the report, I found the error and pushed a fix! New data will be deployed tonight.
