### ISSUE TITLE
Question: How is the data aggregated between for example CA state

### ISSUE THREAD

**Issue by Rathna-K** [lazd/coronadatascraper#131]
a few sources are listed for CA like the below and I thought the link https://github.com/CSSEGISandData/COVID-19 already provides all aggregated data so does that mean the others are duplicates but with more drilldown info like county etc.?

```
https://github.com/CSSEGISandData/COVID-19
http://www.solanocounty.com/depts/ph/coronavirus.asp
http://www.santacruzhealth.org/HSAHome/HSADivisions/PublicHealth/CommunicableDiseaseControl/Coronavirus.aspx
https://www.ventura.org/covid19/
https://www.co.shasta.ca.us/index/hhsa/health-safety/current-heath-concerns/coronavirus
```

**Comment by lazd** [comment]
Yes, the others drill down to the county level. That was the original goal on this project; get as granular as possible. You can view the data at https://blog.lazd.net/coronaglobe/#lat=37.685&long=-116.689
