### ISSUE TITLE
Cross checking of data

### ISSUE THREAD

**Issue by judepayne** [lazd/coronadatascraper#143]
Hi,
coming from [this issue](https://github.com/CSSEGISandData/COVID-19/issues/957) on the Johns Hopkins site.

Wondering if it would be a useful contribution to have cross-checking of data against a secondary source/s, e.g. vs the wikipedia entry before it's added to the timeseries data?

**Comment by lazd** [comment]
Yes, ABSOLUTELY. We'd love to see various sources crosschecked. We already de-dupe, so it's a simple check to say "hey, there are two sources for this data, and the counts don't match." I'll implement this right now and include it in the report.

**Comment by lazd** [comment]
![image](https://user-images.githubusercontent.com/201344/77047548-22478980-6982-11ea-83c6-ddd2e8b1adb7.png)

Thoughts?

**Comment by judepayne** [comment]
Great!
My thought was that if the test fails, it could raise a morning-report style issue on the Johns Hopkins site for the suspicious/ failing subset. Then there are the prices where the scraper can't find a new value so fills in with yesterday's value. Those should be on the report, maybe even take the secondary source/ wikipedia value instead?
Sounds like you are on it! but please let me know if I can help by contributing any of the code

**Comment by judepayne** [comment]
That looks great!
Presumably the source with the highest rating is considered the primary.
You have all the data there to build the summary morning report/ alert I'd envisaged. I think that we need that summary alert of the fails to tell humans on the other end what they need to investigate.

**Comment by lazd** [comment]
Yes, the source with the highest rating wins when duplicates happens. I pushed a report here: https://coronadatascraper.com/#report.json

It's under `scrape->crosscheckReports` -- I think it needs to be up-leveled to the top of the object...

**Comment by lazd** [comment]
Eh, maybe it's fine where it is -- the check happens during the scrape, so it can be reported in the scrape's section of the report.

**Comment by lazd** [comment]
@judepayne can you file another issue for any other functionality, like filing reports, slackbot, or anything else?

**Comment by judepayne** [comment]
Will do! I've checked the report - perfect.
The main issue I find with the JH site is the backlog of PR's those guys have, and the time it takes merge those PR's - leaves the data incorrect often for days. So, the trick is to use this report optimally in their workflow so that PR's don't even have to get raised in the first place.
Do you know what notification would work best for their workflow? (and I will raise another issue here)

**Comment by lazd** [comment]
TBH, I can't speak to that. They're completely overwhelmed..

**Comment by judepayne** [comment]
Yes - I have offered to help with their backlog of PR's.
Ok, I will file an issue here for posting the report to as an automated github issue since that makes the most sense to me.
