### ISSUE TITLE
Tanzania has no country code

### ISSUE THREAD

**Issue by Wikunia** [lazd/coronadatascraper#145]
I just came across that Tanzania does not have it's country code in the `timeseries.csv`.
It should be `TZA` but instead showing `Tanzania`.

**Comment by lazd** [comment]
While you're in there, can you check the other regions that don't return a valid 3 letter ISO 3166-1 alpha-3 code?

"Tanzania"
"The Bahamas" "Gambia, The"
"Faroe Islands"

Might need to edit the override for Faroe Islands: https://github.com/lazd/coronadatascraper/blob/master/tasks/findFeatures.js#L55-L59
