### ISSUE TITLE
output reference for France

### ISSUE THREAD

**Issue by abdoulsn** [lazd/coronadatascraper#161]
Hello, How to modify french output files on this project, granularity levels are not correctly done.

**Comment by claustres** [comment]
Probably related to https://github.com/lazd/coronadatascraper/issues/102.

**Comment by qgolsteyn** [comment]
Could you let me know which granularity you would prefer? The scrapper for France can be found here: https://github.com/lazd/coronadatascraper/blob/master/scrapers/FRA/index.js

**Comment by claustres** [comment]
See my [comment](https://github.com/lazd/coronadatascraper/issues/102#issuecomment-601605950)

**Comment by qgolsteyn** [comment]
Closing to move the conversation to #102
