### ISSUE TITLE
Consider bus factor

### ISSUE THREAD

**Issue by hyperknot** [lazd/coronadatascraper#205]
After today's meeting I just wanted to raise a very simple point: due to the nature of this project, we should aim to make it as simple as possible so that multiple team members understand each part.

Based on the nature of this project, core mainteiners can be out of reach for up-to-2-week periods while the rest of the team need to replace that person.

Picking any technology in our stack which requires very specific domain knowledge is not a good choice for this.

The current architecture, 100% GitHub based is actually quite good in this.

**Comment by hyperknot** [comment]
+1 point here is what will happen to the data in 5 years from now. AWS credits will be over in a year or so and then someone would need to pay for all the AWS infrastructure, just to keep historical data running.

**Comment by ryanblock** [comment]
Redundancy and accessibility of our stack is def important, as is minimization of domain specific knowledge. For example: deep knowledge of AWS, GCP, Kubernetes, etc. should not be required to build. (This is, unfortunately, a curse of much of our industry at this moment.)

Fwiw, we shouldn't kid ourselves: GitHub Actions, for example, requires its own domain knowledge. Fortunately lots of folks have already gotten over the massive learning curve to get it working.

I would argue that anything we adopt should be optimized for a) velocity, b) friction reduction, and c) providing excellent service to the customers we're ultimately building for.

Also keep in mind the goal is not the site we have today, but a globally available end-user facing web app and APIs that can scale to meet enormous demand in the weeks and months to come.

To point out the obvious: many lives will be stake over the next 18 months; if we expect to contribute to disseminating local level pandemic data in a truly helpful way, we'll need a solid, dependable foundation, and that begins with reliable, scalable, deterministically reproducible cloud infra. Which means relying on AWS – and I'd challenge anyone to disprove that assertion.

The current infra setup does not fit the bill for such an effort; for example, git submodules is an excellent way to start, but a decelerant and not a viable long term substitute for writing to a purpose built blob store (S3) and/or database.

Anyhow, I'd encourage everyone to focus on today-problems – we'll deal with tomorrow's problems tomorrow. Today's problem is getting this application to scale up without a rewrite, interruption in scraping service, or significant additional ceremony or barriers to entry.

If you have other alternatives, please do feel free to shout them out!

**Comment by hyperknot** [comment]
I think we are on the same page in this, thanks for the clarification.
