### ISSUE TITLE
Support groupings of counties

### ISSUE THREAD

**Issue by chunder** [lazd/coronadatascraper#234]
At least Idaho and Utah USA seem to be reporting case counts for small collections of counties. I think I've noted other states doing this.

Utah has the "Tri County Area" which contains 3 counties. They report a single case count for all 3. The current scraper divides it by 3 and distributes it to each underlying county. This is sort of misleading and weird.

Maybe we could support assigning a case count to a group of counties instead? Might be more trouble than its worth.

**Comment by lazd** [comment]
Alright, I implemented this, but I'm not happy with the implementation because it's US-centric. See NY: https://github.com/lazd/coronadatascraper/blob/master/src/events/crawler/scrapers/USA/NY/index.js#L108-L117

Thoughts?

**Comment by chunder** [comment]
That API looks great. It should be effective in most of the cases we found where numbers are being rolled up across small groups of counties.

**Comment by lazd** [comment]
Sweet. Can we call this closed? I know you applied it for AK, you eventually got it working, yes?

**Comment by chunder** [comment]
Yup
