### ISSUE TITLE
Alaska is collecting/reporting based on "economic regions" not counties

### ISSUE THREAD

**Issue by chunder** [lazd/coronadatascraper#245]
AK is only reporting 6 “economic regions” which may or may not map to collections of counties. These regions seem important in their normal governance beyond covid19. We might want to consider adding these regions geographical features.

These pages probably have the GIS shapes for the economic regions:

https://dcra-cdo-dcced.opendata.arcgis.com/datasets/alaska-economic-regions (edited) 
http://live.laborstats.alaska.gov/cen/maps.cfm#gis

**Comment by lazd** [comment]
Thanks for implementing this!
