### ISSUE TITLE
2D map not properly filling the browser window

### ISSUE THREAD

**Issue by chunder** [lazd/coronadatascraper#254]
I am seeing the 2D map not properly filling the browser window. I see this on both desktop and mobile. Resizing the browser or reloading the page seems to fix it.

![image](https://user-images.githubusercontent.com/50395/77254309-8043cd80-6c1d-11ea-86e5-2a429b4f9399.png)

**Comment by lazd** [comment]
@chunder what browser is this? Does it happen consistently if you visit https://coronadatascraper.com/#features.json directly vs visiting https://coronadatascraper.com/ and accessing it from the menu?

**Comment by lazd** [comment]
Reproduced in Firefox -- looks like it only happens when you visit the https://coronadatascraper.com/#features.json directly

**Comment by chunder** [comment]
That agrees with my experience, yes. Also, this seems to be a new issue. I only noticed it yesterday night, when the "Percent of population infected" legend appeared.

**Comment by lazd** [comment]
Fixed and deployed!
