### ISSUE TITLE
VA is available by county 

### ISSUE THREAD

**Issue by debusklaneml** [lazd/coronadatascraper#264]
You can likely scrape this information here: http://www.vdh.virginia.gov/coronavirus/

**Comment by DavidGeeraerts** [comment]
[Slack](https://sars-cov-2covid-19.slack.com/archives/C0101BDEEDV/p1584978383008400)

**Comment by lazd** [comment]
Closed by https://github.com/lazd/coronadatascraper/pull/281, thanks @aed3!
