### ISSUE TITLE
Website didn't update Sunday night 3/22. On Monday 3/23 the site still shows 3/21 data.

### ISSUE THREAD

**Issue by chunder** [lazd/coronadatascraper#276]
My fix for Miami-Dade county was merged yesterday, but it’s showing 0 cases on the site right now. When I run FL locally, it’s getting the right data: { county: 'Miami-Dade County', cases: 227, tested: 1801, deaths: 0 },

**Comment by chunder** [comment]
I also note that the time series csv shows 3/21 as the last date.

**Comment by lazd** [comment]
On it!

**Comment by lazd** [comment]
Updated!
