### ISSUE TITLE
Yarn issue

### ISSUE THREAD

**Issue by prem121121** [lazd/coronadatascraper#279]
I am getting this error when the command "yarn install" or "yarn start" are run. 
"Yarn requires Node.js 4.0 or higher to be installed."

I installed Node.js and Yarn as well. please assist. thanks

**Comment by lazd** [comment]
It sounds like you have some node issues. Unfortunately, we're too busy to walk you through this and it is not an issue with the project. Please check StackOverflow and other resources.

**Comment by lazd** [comment]
You might try using `nvm` to manage your installed version of node.
