### ISSUE TITLE
Arkansas Data

### ISSUE THREAD

**Issue by tautme** [lazd/coronadatascraper#282]
Hello,

Thanks for your work in this time of change.

I notice your data on Arkansas, USA is not at the county level. They have been changing their website.

I am in contact with the Arkansas Health Department and wondered if you could recommend the  best practice format, for you to collect county level data?

They are also reporting the number of negative cases. Will you consider collecting negative counts also?

Regards,

Adam Hughes

**Comment by paulboal** [comment]
@tautme - Is there a publicly available source for that data?  The website here doesn't make it very easy to access and doesn't include negative counts: https://www.healthy.arkansas.gov/programs-services/topics/novel-coronavirus

**Comment by tautme** [comment]
@paulboal  Sorry, They just moved all the data to an arcgis dashboard in the "Status Updates" link. The negative cases are there.
https://adem.maps.arcgis.com/apps/opsdashboard/index.html#/f533ac8a8b6040e5896b05b47b17a647
Could you give me an example of a website that is easy to access, data? Is the Texas site easy to scrap? https://dshs.texas.gov/news/updates.shtm#coronavirus

**Comment by lazd** [comment]
Closed by https://github.com/lazd/coronadatascraper/pull/293, AR is now on the map!
