### ISSUE TITLE
Italy tested: add the TESTED from last column "tamponi"

### ISSUE THREAD

**Issue by aledettaale** [lazd/coronadatascraper#302]
Hello. In your data csv: https://coronadatascraper.com/#data.csv 
for Italy you use:
https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv
In this you can take the TESTED too: last column tamponi
Thanks!

**Comment by lazd** [comment]
@aledettaale sounds good, can you send a PR?

**Comment by aledettaale** [comment]
I'll try it now. I am new to GitHub but I have been analyzing data from Italy since the end of February.
Then I write you something else strange or wrong found in official world map (https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6)

**Comment by aledettaale** [comment]
For denominazione_regione > state: Emilia Romagna is better Emilia-Romagna (for maps)

**Comment by lazd** [comment]
Fixed in d4f2d428317c0e47085a8cbbcbd1310b44991cc1
