### ISSUE TITLE
Switzerland Data

### ISSUE THREAD

**Issue by chschoenenberger** [lazd/coronadatascraper#305]
Hi Folks

Great work. I'm thinking about moving to your datasource from JHU. I saw that for Switzerland you still get the JHU data. There's a guy that scrapes multiple datasource in Switzerland. Maybe you could either get his data or use his scraper for Switzerland. This includes data on canton-level:
https://github.com/daenuprobst/covid19-cases-switzerland

Thanks and keep up the great work
Chris

**Comment by lazd** [comment]
Yes, there is another data source we're using, but haven't scraped the entire thing yet: https://github.com/openZH/covid_19/

Can you send a PR adding the rest of the data at our existing source?

**Comment by qgolsteyn** [comment]
I almost have a scraper done for this source. Will push soon.
