### ISSUE TITLE
KS should not return all 0s if it gets an error fetching the source PDF

### ISSUE THREAD

**Issue by chunder** [lazd/coronadatascraper#307]
It should return no results, not 0s for all counties.

```
      const body = await fetch.pdf(this.url);
      if (body === null) {
        // throw new Error(`No data for ${date}`);
        return geography.addEmptyRegions([], this._counties, 'county');
      }
```

**Comment by chunder** [comment]
@paulboal ^^

**Comment by paulboal** [comment]
Question @chunder - when there's no content, should the parser function just `return [];` or something else?  I'll get this fixed.

**Comment by chunder** [comment]
Good question. @lazd ?

**Comment by paulboal** [comment]
Looks like this was already resolved.  This can be closed.

**Comment by lazd** [comment]
Sounds like this is related to #374, adding a note here.
