### ISSUE TITLE
Questions about data model, sources, aggregation, update

### ISSUE THREAD

**Issue by piccolbo** [lazd/coronadatascraper#310]
Hey sorry for all these questions. I am  a data scientist maintaining Yet Another Statistical Graphics Visualization at https://piccolbo.shinyapps.io/covid-19/. Looking to jump ship from JHU as data source 

1. What is your refresh rate
2. Do you do aggregates for us or not? For example if you have 99% county coverage in CA, is there a CA entry? If there is, is it a sum of counties, separate source, combination? Same question for state to country level and for other countries? Would love to have one uniform answer
3. When you have multiple sources for one geography do you: pick one, average, pick both?

Happy to summarize the answer for the README unless I missed something.

Thanks!

**Comment by lazd** [comment]
1. 9PM daily, we should document that somewhere
2. Yes, look at the `aggregate` field in the data and check the README which documents it https://github.com/lazd/coronadatascraper#writing-a-scraper
3. Yes, we pick the source with the highest priority, it's documented in the README https://github.com/lazd/coronadatascraper#writing-a-scraper

We have #49 open to document this properly, can you help?

Thanks!

**Comment by piccolbo** [comment]
Thanks for your quick answer. Point by point

1. Great, I will take care of that
2. Can't really find it, will jump on #49 see if we can clarify there. The word aggregate is  in there, but not the info I need.
3. Ok so there is a priority field, but what criteria to decide value? It looks, superficially, that the scraper author can put a number. I am sure it's more thoughtful than that.

**Comment by piccolbo** [comment]
It looks like from discussion in #49 "aggregate" means something else, it's a property of a source (an aggregator of data) not a data point. In the data analysis world aggregation are statistics of the data. It doesn't mean it's the only meaning of the word. Others call that a roll-up. It looks like you don't have any derived statistics in your data or roll-ups. The sources may be doing that (summing their scrape of the county level data) but you are not. On the other hand, you seem to provide at least for US, data at all relevant roll-up level, county, state, country. So that simplifies things (as opposed JHU where some rollups are up to the user and some aren't) and that clarifies the issue for me. Issue of priority is covered in #83 so I am going to close this issue. Thanks

**Comment by lazd** [comment]
@piccolbo so Priority and Ratings are different -- Priority is, as you said, decided by the author. For instance, if we have all counties covered with data from a state, we give that scraper a higher priority so it overrides any other data source for the same data, because we're getting it straight from the horses mouth.

I was unaware of `aggregate`'s usage, sounds like we should rename it to `rollup`?

We do indeed roll-up county-level data to generate state-level data -- anywhere you see `transform.sumData()`, that's what is happening: https://github.com/lazd/coronadatascraper/search?q=sumData&type=

**Comment by piccolbo** [comment]
If it's a sum, you could call it roll-up but aggregate is clear to me. But my understanding was that aggregate means not from an aggregator source, which is different. 2+2 is a rollup, aggregate or statistics (2,2) is what an aggregator does, accumulating the data. Clearly I am not fully getting it yet and I am under pressure to replace JHU because they just f&*(&  all State data users last night. Sorry I will be more cooperative as soon as I have that fixed.. #83 says priority is computed from ratings, which makes a lot of sense. Are you changing the tune here? Anyway your data is very simple, dupes are taken out , main rollups are built in, no complaints here. I'd add one column that says if row is for a county, state or country. Easy to compute, but not with SQL. Imagine you want to support sql queries like select all US state, `select * where  level = "state", country = "US" and you get data for CA, NY, WA etc. I am doing things in R so I just how look at what col is NA or not, no problem.  It'd be nice to have stat assessment of data quality, if I come up with something I will share.

**Comment by piccolbo** [comment]
@lazd somebody asked if you meant 9pm PT. Good question.
