### ISSUE TITLE
State `DC` and county `District of Columbia` are redundant

### ISSUE THREAD

**Issue by chunder** [lazd/coronadatascraper#312]
Ok, so we have a state called `DC` and a county called `District of Columbia` in our published json/csv. We are actively scraping the state DC. It looks like the county District of Columbia was being sourced through JHU previously, and stopped getting updates on 3/11. Do we want/need to merge these somehow? Or just ignore for now?

**Comment by lazd** [comment]
I think I found the issue; we're treating `District of Columbia` as a county if it comes from JHU, and as a state elsewhere.

**Comment by lazd** [comment]
@chunder fix pushed, I verified it's working by checking timeseries data. Let me know if you see any issues!

**Comment by lazd** [comment]
![image](https://user-images.githubusercontent.com/201344/77466373-6940df00-6dc7-11ea-9ac3-daa3348ee369.png)
Looking right on the map now

**Comment by chunder** [comment]
Cool. I think it was already looking good on the map. Our state scraper was working fine. But our CSV/json/etc was outputting 2 records: one for state DC and one for District of Columbia.

**Comment by lazd** [comment]
Yes, that should be fixed!
