### ISSUE TITLE
State vs County data on map

### ISSUE THREAD

**Issue by NateBaldwinDesign** [lazd/coronadatascraper#320]
Unclear if this is a bug or as intended, however this causes a poor experience.
Appears as though state of New York either a) extends beyond the county boundaries or b) certain counties are not included on map. 
Result: Looks like an odd sliver of geography that has all of NY State's data associated with it. 

Recommendation: If counties are available, show the counties only. Otherwise offer a toggle to view State-level data only.

![image](https://user-images.githubusercontent.com/13972198/77481223-d0bb5680-6de8-11ea-91bf-72d90f133a22.png)

**Comment by lazd** [comment]
Fixed!
