### ISSUE TITLE
Fix historical NYC data, transition to borough/county level reporting

### ISSUE THREAD

**Issue by alexmill** [lazd/coronadatascraper#323]
The "New York County, NY, USA" (i.e., Manhattan) timeseries data has a major discontinuity in March. Seems to be due to new borough/county level reporting.

![Screenshot 2020-03-24 at 5 43 24 PM](https://user-images.githubusercontent.com/2365548/77487057-00715b00-6df7-11ea-9145-4272bc43adbc.png)

**Comment by psylum** [comment]
i've been manually saving the case/death breakdowns from the NYC pdf since the 18th. not sure if there's a preferred way to provide that data for backfill into their time series data.

**Comment by lazd** [comment]
Yeah, we need to go back and edit the previous scrapers that lumped everything into `New York County`

**Comment by lazd** [comment]
Ok I figured out the problem, thanks for the report!
