### ISSUE TITLE
Bergen County, NJ, USA stopped updating on 3/19

### ISSUE THREAD

**Issue by alexmill** [lazd/coronadatascraper#325]
See current data here: https://healthgis.co.bergen.nj.us/portal/apps/webappviewer/index.html?id=3ee51425865a4d80bc4a3b8b51a4497d

P.S. I don't know if there's a better place to log these issues with the historical data. These fixes currently have to be done manually, so I'm happy to create a new issue for each instance of bad data I find. Or, if there's a more standardized place to report them, let me know.

**Comment by alexmill** [comment]
PS. the reason I'm seeing these missing data is because I'm trying to make these plots, which make them easy to spot:
 
![download (2)](https://user-images.githubusercontent.com/2365548/77488384-af636600-6dfa-11ea-86e6-c3b119d9903a.png)

**Comment by lazd** [comment]
Fixed by  8457887102dd4eca3a91f159958582a486fc5831
