### ISSUE TITLE
The data for Dallas County, Texas, is out of date

### ISSUE THREAD

**Issue by handcoding** [lazd/coronadatascraper#326]
Going by [the site](https://coronadatascraper.com/#features.json), it says that Dallas County, Texas, has `33 cases`. 

But as of when I write this on March 24, 2020, [Dallas County, Texas has `169 confirmed cases`](https://www.dallascounty.org/departments/dchhs/2019-novel-coronavirus.php) of the coronavirus.

**Comment by cmcjacob** [comment]
As of today, state of Texas moved their reporting to ARCGIS. The scraper will need updated

**Comment by lazd** [comment]
Fixed! Though I see 131 for 2020-3-24, and 169 for 2020-3-25.
