### ISSUE TITLE
Missing China

### ISSUE THREAD

**Issue by zbraniecki** [lazd/coronadatascraper#336]
The `timeseries-byLocation.json` seems to be missing `CHN` as a country.

Is that a bug or is it intentional? If it's intentional, is it expected that summing up `CHN` state values provides a good approximation for `CHN`?

**Comment by cristipp** [comment]
Also missing Wuhan.

**Comment by zbraniecki** [comment]
I confirmed that summing up states gives a good values for the whole country comparable to other sources.

**Comment by cburkins** [comment]
Agree, would be convenient to have a single entry for China to make for easier comparisons against other country-level data

**Comment by lazd** [comment]
@cristipp Wuhan is a city and was never in any dataset. You're looking for `Hubei, CHN`

**Comment by cburkins** [comment]
I can indeed see it, now.  Thanks so much.
