### ISSUE TITLE
NJ scrapes stale data

### ISSUE THREAD

**Issue by edwlook** [lazd/coronadatascraper#341]
Looks like NJ is fetching for a CSV file that only contains data for 3/19. Is there a way to find the updated CSV url to pull from (and also not have to keep changing the URL every day)? https://github.com/lazd/coronadatascraper/blob/master/src/events/crawler/scrapers/USA/NJ/index.js#L28

Also curious if that CSV is from the same source powering the dashboard here https://www.nj.gov/health/cd/topics/covid2019_dashboard.shtml

**Comment by alexmill** [comment]
Related to https://github.com/lazd/coronadatascraper/issues/325

**Comment by lazd** [comment]
Fixed by  8457887102dd4eca3a91f159958582a486fc5831
