### ISSUE TITLE
timeseries.json get over 700k cases in sum on 2020-3-24

### ISSUE THREAD

**Issue by a0s** [lazd/coronadatascraper#343]
But https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6 gets 424k only!

I downloaded https://coronadatascraper.com/timeseries.json, selected records under key "2020-3-24" and summed all of it to get total counter for 2020-3-24. And i got
```
2020-3-24 => {"cases"=>771871, "deaths"=>30283, "active"=>713451, "tested"=>780157, "recovered"=>28137}
```
It seems little falsy ... Did i miss something?

**Comment by chschoenenberger** [comment]
See https://github.com/lazd/coronadatascraper/issues/100
Especially for the US, there's data that is duplicated. There's several aggregation levels available. If you sum over all data you count confirmed for each county + all states + the whole country

**Comment by lazd** [comment]
Yeah @a0s you need to pay attention to the `aggregate` field. If you see a country with `aggregate: 'state'`, ignore all its states. If you see a state with `aggregate: county`, ignore all its counties, etc.

**Comment by a0s** [comment]
@lazd thank you, i missed this field when saw first time to json!
