### ISSUE TITLE
New visualization site

### ISSUE THREAD

**Issue by piccolbo** [lazd/coronadatascraper#355]
https://piccolbo.shinyapps.io/covid-19/
Features: smoothed (Friedman's supersmoother) and unsmoothed plots, by country or US State. Doubling rates and projection at 15 days. Population normalized numbers. 
Use best statistical graphics practices (as opposed to tableau chartjunk), exclusively log scale, show new cases to support positive thinking (cumulative only goes up), inline labels for dense plots.

**Comment by lazd** [comment]
Looks very cool! Can you send a PR to add it to `site/index.html`?

**Comment by piccolbo** [comment]
Thanks, wanted make sure that wasn't a generated file or something. Will do.
