### ISSUE TITLE
Canada and Switzerland subregions are merged 

### ISSUE THREAD

**Issue by divisia** [lazd/coronadatascraper#359]
Canada (CAN) and Switzerland (CHE) subregions are mixed. CAN is missing and all of Canadian states showing up under CHE.

**Comment by zbraniecki** [comment]
I think it may be fixed as of today?
I see 13 regions marked as `*, CAN` in the data plus `"Total, CAN"` which is likely a bug (it should be a country not a state - I reported it as #405.

**Comment by lazd** [comment]
@divisia sounds like a cache issue -- you have to hard refresh sometimes after we deploy.
