### ISSUE TITLE
Countries listed by name in timeseries-byLocation.json

### ISSUE THREAD

**Issue by NickSto** [lazd/coronadatascraper#361]
I've noticed there are several instances where the timeseries data has a country keyed both by its ISO-3166 country code *and* its common name:

|key|code|
|-----|------|
|`US`|`USA`|
|`Bahamas, The`|`BHS`|
|`Cape Verde`|`CPV`|
|`East Timor`|`TLS`|
|`The Gambia`|`GMB`|
|`Republic of the Congo`|`COG`|

Also, a couple countries are present only by their full names, *not* their country codes:
|key|code|
|-----|------|
|`Syria`|`SYR`|
|`Laos`|`LAO`|

**Comment by lazd** [comment]
Thanks, @NickSto! I bet you'll find JHU is providing the ones that are keyed off something other than the ISO-3166 alpha 3 code... Can you confirm the sources for each item you noted above?

Note that the US issue should be fixed already.

**Comment by NickSto** [comment]
@lazd Yep, JHU is the source for everything I mentioned except `USA`, which is from `https://covidtracking.com/api/states`.

**Comment by NickSto** [comment]
Wow that was quick, thanks!

**Comment by NickSto** [comment]
Okay looks like we got a regression. I just checked and there's a `Burma` key now.

**Comment by lazd** [comment]
@NickSto ok that doesn't sound like a regression, more like another case we didn't handle. I'll take a look.

**Comment by lazd** [comment]
So should Burma be MMR? It's it called Myanmar now? https://www.iso.org/obp/ui/#iso:code:3166:MM

**Comment by NickSto** [comment]
Yeah, MMR seems to be the ISO code for that country, whatever you prefer to call it. Thanks for taking a look.
