### ISSUE TITLE
Visualization by US State

### ISSUE THREAD

**Issue by travishaby** [lazd/coronadatascraper#369]
After JHU broke their data format, I thought my little visualization was going to be a pain in the ass to rebuild--then I found y'all's API! Thanks so much for providing a great source for this data--was really easy to shape into what I needed.

Here's my simple visualization of COVID-19 cases by US state, hosted on Glitch: 
https://covid-19-by-states.glitch.me/ 
(it may take a sec for the container to start up on the first request if it hasn't recently been used)

Will try to find some time soon to tackle a needed feature to give back to the project--thanks again!

**Comment by lazd** [comment]
@travishaby go ahead and send a PR adding a link to your project!
