### ISSUE TITLE
geography.addEmptyRegions can easily mistakenly infill all counties with 0 cases in a state

### ISSUE THREAD

**Issue by chunder** [lazd/coronadatascraper#374]
So I just realized that `geography.addEmptyRegions` is a bit dangerous.

If a scraper gets confused by a change in the source page, it will sometimes fail to find any counties. That’s cool, returning no results is a safe/conservative thing to do.

But then most county level state scrapers call `addEmptyRegions`. Which sees no data. And backfills 0 for every county.

I wonder if `addEmptyRegions` should throw an error if it gets called with *no* actual counties.

**Comment by lazd** [comment]
This is true... I agree, we should throw if no data is present!

**Comment by chunder** [comment]
PR created: https://github.com/lazd/coronadatascraper/pull/421

**Comment by chunder** [comment]
Now we won't be outputting `0` cases if a scraper breaks. Will the map properly reflect the prior day's data if the time series has a missing entry for the final day?

**Comment by lazd** [comment]
Fixed in #374
