### ISSUE TITLE
Data has a gap between 2020-3-11 and 2020-3-24

### ISSUE THREAD

**Issue by zbraniecki** [lazd/coronadatascraper#375]
There's a gap for all chinese states between `2020-3-11` and `2020-3-24`:

```json
      "2020-3-11": {
        "cases": 1356,
        "deaths": 8,
        "recovered": 1282,
        "active": 66,
        "growthFactor": 1.0022172949002217
      },
      "2020-3-24": {
        "cases": 1428,
        "deaths": 8
      },
```

**Comment by zbraniecki** [comment]
Same for Germany:

```json
      "2020-3-11": {
        "cases": 1908,
        "deaths": 3,
        "recovered": 25,
        "active": 1880,
        "growthFactor": 1.3095401509951956
      },
      "2020-3-24": {
        "cases": 32986,
        "deaths": 157
      },
      "2020-3-25": {
        "cases": 37323,
        "deaths": 206,
        "growthFactor": 1.131480021827442
      }

```

**Comment by zbraniecki** [comment]
List of affected countries: `[CHN, THA, JPN, SGP, NPL, MYS, KHM, LKA, DEU, FIN, ARE, PHE, IND, SWE, BEL, EGY, LBN, IRQ, OMN, AFG, BHR, KWT, DZA, HRV, AUT, ISR, BRA, GEO, GRC, MKD, NOR, ROU, EST, NLD, SMR, BLR, ISL, LTU, MEX, NGA, IRL, LUX, MCO, QUT, ECU, AZE, ARM, DOM, IDN, PRT, AND, LVA, MAR, SAU, SEN, ARG, CHL, JOR, UKR, HUN, LIE, POL, TUN, BIH, SVN, ZAF, BTN, CMR, COL, CRI, PER, SRB, SVK, TGO, MLT, BGR, MDV, BGD, PRY, ALB, CYP, BRN, BFA, VAT, MNG, PAN, IRN, KOR, DNK, CZE, TWN, VNM, RUS, MDA, BOL, HND, COD, CIV, JAM, TUR]`.

It may be important to not update your JSON until that gets fixed.

**Comment by lazd** [comment]
Sounds like a JHU data issue... Will investigate tomorrow

**Comment by lazd** [comment]
Fixed by 4cf6d488b86ced1a6f1c9a3b7bde7a0f55aa9195

**Comment by piccolbo** [comment]
Still see the gap for TUR, cases, most of march

**Comment by lazd** [comment]
Not deployed yet
