### ISSUE TITLE
Recovered cases data

### ISSUE THREAD

**Issue by zbraniecki** [lazd/coronadatascraper#388]
It seems that we're backing out of recovered data.

Is the consensus that we cannot find sources of data to provide continuous information on recovered data?

**Comment by zbraniecki** [comment]
Example of recovered cases tracker - https://plague.com/

**Comment by DavidGeeraerts** [comment]
It depends on the State and the Counties in the USA. It's not consistent in reporting, so some states will have the aggregation of County recovered, some report County level, etc.
It's simply a data reporting mess.

**Comment by zbraniecki** [comment]
I know, but same is for other factors - there's no standardized model for "cases" or even "deaths" (different countries report different statistics) or "testing". So maybe having some "recovered" available even if the method of calculating them differs per country is better than having none?

**Comment by lazd** [comment]
If sources don't provide it, we don't capture it. If they do, we include it.

We are not in the business of calculating anything except `active` (based on `deaths` and `recovered`), and even that is super shaky. 

However, if you see a source that we're already scraping that is providing recovered data, but we're not including it, then file an issue and we can add it.

**Comment by zbraniecki** [comment]
> We are not in the business of calculating anything except active (based on deaths and recovered), and even that is super shaky.

I'd argue we shouldn't calculate that either, but that's a topic for #389.

> However, if you see a source that we're already scraping that is providing recovered data, but we're not including it, then file an issue and we can add it.

Right, so maybe my issue should be renamed to "Recovered cases missing for many major regions." - and the approach would be to look for recovered data since JHU stopped providing it.

**Comment by zbraniecki** [comment]
This source seems to still show `recovered` - https://www.worldometers.info/coronavirus/
