### ISSUE TITLE
Kinsa fever data

### ISSUE THREAD

**Issue by zbraniecki** [lazd/coronadatascraper#404]
While not exclusively COVID-19 related, Kinsa fever data may be a useful raw datapoint for us as well: https://healthweather.us/

It uses the network of smart thermometers to show the deviation of fever frequency from the norm. I imagine we could collect this datapoints as two data:

```
{
  "2020-3-25": {
    "kinsa": {
      "typical_range": [0.032, 0.042],
      "expected": 0.039,
      "observed": 0.031,
    },
  },
}
```

this would tell us that according to Kinsa, `3.1%` of a given population has a fever on that day, and it's a deviation compared to expected `3.9%`.

I understand that collecting a single company's data may be awkward, but I think it's a good data point to accumulate and use for evaluating the effect of social distancing and fever is a good predictor of coronavirus.

**Comment by lazd** [comment]
Hmmm, very interesting and likely something you could layer on for your own visualizations, but outside of the scope of the data this project is trying to report.
