### ISSUE TITLE
Florida deaths not captured

### ISSUE THREAD

**Issue by DavidGeeraerts** [lazd/coronadatascraper#46]
Florida deaths is not being captured. Should see a # for deaths for Florida.
(*Florida is only reporting deaths at the state level, not at the county level.)

```
city | county | state | country | cases | deaths
-- | --| FL | USA | 31 | -- | -- | -- | -- | -- | --
```

SOURCE: http://blog.lazd.net/coronadatascraper/data.csv
*as of this post.

**Comment by lazd** [comment]
@DavidGeeraerts I see. We're pulling state level data from CDC right now. Let's see what we can do about this...

**Comment by PCastleton** [comment]
In Florida, the website has 5 more cases than the scraper (100 vs 95).  That may just be a more recent update.  More to the issue, the scraper is having trouble bucketing all the cases into counties.  Currently, 31 of the 95 scraper cases that have no county associated.

**Comment by PCastleton** [comment]
Correcting error above:  The 31 was the CDC case count.  Florida Health shows 100.  Apologies confusion.

**Comment by lazd** [comment]
@PCastleton deaths are no longer reported. This is their latest data: https://opendata.arcgis.com/datasets/b4930af3f43a48138c70bca409b5c452_0.csv

The scraper has been updated to use this data.
