### ISSUE TITLE
MA Suffolk County count wrong on 2020-03-21

### ISSUE THREAD

**Issue by dkulp2** [lazd/coronadatascraper#461]
Suffolk County, MA should have 108, not 10 on March 21. This was a non-standard named file so perhaps it was manually entered and mis-keyed?

Attached is source reference via wayback.

[covid-19-case-report-3-21-2020-acc.docx](https://github.com/lazd/coronadatascraper/files/4397134/covid-19-case-report-3-21-2020-acc.docx)

**Comment by lazd** [comment]
Good catch, it's showing up on two separate columns in the parser. I think I got it, and I fixed up the feature region for `Dukes and Nantucket`.

Can you validate the attached data and make sure it's correct for 2020-3-20 to 2020-3-27?

[timeseries-check.zip](https://github.com/lazd/coronadatascraper/files/4397604/timeseries-check.zip)

**Comment by dkulp2** [comment]
I was even going to say anything about the crazy Dukes & Nantucket thing, so thanks for addressing it, but now there's a mistake there: March 25 shows 315 instead of 3.

**Comment by dkulp2** [comment]
I wasn't even going to say anything about the crazy Dukes & Nantucket thing, so thanks for addressing it, but now there's a mistake there: March 25 shows 315 instead of 3.

**Comment by dkulp2** [comment]
Additional errors
Deaths in MA statewide:
 - March 25 is 15, not 5
 - March 28 is 44, not 4
 - March 29 is 48, not 8

Thanks!
