### ISSUE TITLE
Using this data

### ISSUE THREAD

**Issue by chfritz** [lazd/coronadatascraper#474]
As suggested, just opening a ticket to let you know that we are using this data in https://bibbase.org/other/covid-19. Thank you very much for the effort, us and our users really appreciate it. There are so many really great visualizations already. The focus of ours is to plot the number of cases over time by region and to compute the 2nd gradient of cases (acceleration/deceleration of spread).

**Comment by lazd** [comment]
Awesome, nice work! Can you send a PR along to add this to `site/index.html`? Thanks!
