### ISSUE TITLE
NY Times data

### ISSUE THREAD

**Issue by kdn88** [lazd/coronadatascraper#487]
Not sure if this is incorporated in the scraper dataset, but NY Times is publishing their data on github.  Maybe common source, but just thought i'd bring it up.

https://github.com/nytimes/covid-19-data

**Comment by lazd** [comment]
Yes, it's already in the scraper and cross-checked/de-duped against everything. 

https://coronadatascraper.com/#crosscheck
https://coronadatascraper.com/#sources
