### ISSUE TITLE
a few more ISO3166 names

### ISSUE THREAD

**Issue by greg-minshall** [lazd/coronadatascraper#78]
it seems like Congo (Brazzaville) and Hong Kong have ISO3166 codes (COG and HKG).  (at least according to wikipedia).  i think that would just leave Kosovo without a code.

**Comment by lazd** [comment]
So @saralioness and I looked at Congo: https://github.com/lazd/coronadatascraper/commit/e4a4cc011797785b763ca911f3dfd6778193484f

And a few others: https://github.com/lazd/coronadatascraper/commit/8de5f5e466cc4557f30e01e1f974075239249302

We wrote `KOS` for for Kosovo. Thoughts?

**Comment by greg-minshall** [comment]
i'd probably leave Kosovo "Kosovo", so it's clearly *not* a 3166 code.  (thanks, btw, for the pointer to 3166 -- i hadn't realized the source of these codes.)

also, you seem to want Palestine to be "PSR".  it seems like 3166 defines it as PSE.

**Comment by lazd** [comment]
I think that's a typo, thanks! Can you send a PR to fixup Palestine and Kosovo?

**Comment by hyperknot** [comment]
I've created an ID system especially for these issues, have a look:
https://github.com/hyperknot/country-level-id

Kosovo would be **id0:XK**
For Congo there is **id0:CD** Democratic Republic of the Congo and **id0:CG** Republic of the Congo (id3).

**id0:PS** Palestine (id3)
 - **id1:GAZ** Gaza
 - **id1:WEB** West Bank

**Comment by greg-minshall** [comment]
nice!

i'll mention that [https://en.wikipedia.org/wiki/ISO_3166-2](url) ISO3166-2 includes "principal subdivisions" of countries, and, so, might be what you would use when they exist?  Gaza, for example, would be, by (my reckoning of) this, PS-GZA.
