### ISSUE TITLE
Palestine and Kosovo codes

### ISSUE THREAD

**Issue by greg-minshall** [lazd/coronadatascraper#88]
Palestine in ISO 3166 is defined as "PSE" (currently the code uses "PSR").

also, at least the World Bank seems to define Kosovo as "XKX", so maybe that would be a good code to use there.

**Comment by lazd** [comment]
Thanks, @greg-minshall! Can you send a pull request correcting them? The overrides live here: https://github.com/lazd/coronadatascraper/blob/master/lib/transform.js#L10-L28
