### ISSUE TITLE
MD scraper broken

### ISSUE THREAD

**Issue by lazd** [lazd/coronadatascraper#89]
Sever returns:
```
{"status":"Failed","error":{"message":"Failed while trying to get item information","code":400,"request":"https://www.arcgis.com/sharing/rest/content/items/ca77764e722c442986ef6514da88411c?f=json","response":"Item does not exist or is inaccessible.","timestamp":"2020-03-16T23:11:04.078Z"},"generating":{}}
```

@SteveWallace can you look at this?

**Comment by SteveWallace** [comment]
Something went wrong with a merge, that's LA not MD. The MD code from my PR last night is gone

**Comment by lazd** [comment]
@SteveWallace oh no! I may have messed it up.

**Comment by SteveWallace** [comment]
no biggie, I'm about to delete and refork to fix a bunch of issues with the submodules. After that I'll submit a PR with the proper LA  state code and the MD code

**Comment by SteveWallace** [comment]
#93
