### ISSUE TITLE
Backfill time series data

### ISSUE THREAD

**Issue by lazd** [lazd/coronadatascraper#9]
Using static sources (JHU), backfill the time series to the start of the start of the pandemic.

**Comment by mark-otaris** [comment]
In case other sources of machine-readable historical data for countries independent of JHU CSSE are useful:

* [Reuters’s map](https://graphics.reuters.com/CHINA-HEALTH-MAP/0100B59S39E/index.html) ([JSON](https://d3sl9l9bcxfb5q.cloudfront.net/json/corona-regionwise)) goes back to December 31
* Our World in Data has [corrected data](https://ourworldindata.org/coronavirus-source-data) transcribed to CSV from WHO’s situation reports
* [WHO’s dashboard](https://experience.arcgis.com/experience/685d0ace521648f8a5beeeee1b9125cd) ([CSV](https://opendata.arcgis.com/datasets/84338c7c0c0b458dbbd7cdbc9e1646e2_0.csv)) has historical case counts, but not deaths or recovered

**Comment by lazd** [comment]
Timeseries data is now generated with `yarn timeseries`!
