### ISSUE TITLE
PA scraper broken

### ISSUE THREAD

**Issue by lazd** [lazd/coronadatascraper#90]
Looks like some HTML moved around.

@osvyg can you investigate?

**Comment by SteveWallace** [comment]
PA changed their html to use a table instead of a list looks like.

**Comment by lazd** [comment]
@SteveWallace if you wanna fix this one, go ahead and do so! Please remember to maintain backwards compatibility https://github.com/lazd/coronadatascraper#what-to-do-if-a-scraper-breaks

**Comment by lazd** [comment]
I'm on it!
